server:
  listen_address: ":9118"

scheduler:
  # How often all domains are refreshed
  refresh_interval: 6h

  # Number of concurrent workers
  worker_count: 5

  # Timeout for each RDAP/TLS request
  request_timeout: 10s

rdap:
  # IANA RDAP bootstrap
  bootstrap_url: "https://data.iana.org/rdap/dns.json"

  # Retry count for failed requests
  max_retries: 3

tls:
  enabled: true
  port: 443

domains:
  - name: justicealign.com
  - name: sesameindia.com
  - name: truecoverage.com
  - name: speridian.com
  - name: benefitalign.com
  - name: inshura.com
  - name: kphari.com
  - name: services4patentattorneys.com
  - name: truebluecoverage.com
  - name: abcbrokerages.com
  - name: speridiano360.com
  - name: brokerengage.net
  - name: speridian.org
  - name: benefit-test.com
  - name: truecoverage-test.com
  - name: casexellence.org
  - name: inshura-test.com
  - name: casexellence.com
  - name: xellinc.com
  - name: Digi360.ai
  - name: o360speridian.com
  - name: o360employee.com
  - name: o360project.com
  - name: finalign.com
  - name: digi360.ai
  - name: passipms.com
  - name: speridianlabs.com
  - name: casexellence.ai
  - name: trueacapartner.com
  - name: e-village.in
  - name: o360speridian.com
  - name: dishaabhiyan.org
  - name: topshelfmarketer.com
  - name: digitalnext.ai
  - name: digitalnow.ai
  - name: usbenefitsportal.com
  - name: Speridianglobalholdings.com
  - name: ehealthcareoptions.net
  - name: business-advantage.net
  - name: enrollinobamacare.com
  - name: acainsurancerates.com
  - name: reliablehealthpartners.com
  - name: thrivehealthbenefits.com
  - name: ascendhpinc.com
  - name: xellbenefits.com
  - name: ehealthcareoptions.com
  - name: beaconpro.in
  - name: xelleration.com
  - name: mvpconsultingplus.com
  - name: abcbrokerages.com
  - name: helix.solutions
  - name: helixmail.com
  - name: helixbusinesssolutions.com
  - name: micelliinsurance.com
  - name: locthoinsurance.com
  - name: salaminsurance.org
  - name: dniservicesllc.com
  - name: reliableriskmg.com
  - name: luminexbm.com
  - name: topshelfmarketers.com
  - name: topshelfinc.us
  - name: truecoveragehealth.com
  - name: truecoveragecare.com
  - name: truecoveragevalue.com
  - name: reliablemedicarepartners.com
  - name: rhpmedicare.com
  - name: acarewardplans.com
  - name: getacabenefits.com
  - name: Xellconnect.com
  - name: xellsupport.com
  - name: hhpins.com
  - name: harmonyhplans.com
  - name: assuredpriorities.com
  - name: friendlyhealthcarecompany.com
  - name: engagecloud.app
  - name: engagecloud.ai
  - name: fmreliablehealthcompany.com
  - name: reliablehealthpartners.info
  - name: ascendhealthpartners.info
  - name: ehealthcareoptions.info
  - name: thrivehealthbenefits.info
  - name: ancillaryenroll.com
  - name: trustedhomeprotection.net
  - name: trustedcoverage.net
  - name: trustedfinancialhelp.net
  - name: trustedhomeservice.net
